### ISSUE TITLE
Derjenige, der das Buch hat: bitte references.bib im work-Ordner vervollständigen

### ISSUE THREAD

**Issue by IntegralDomain** [IntegralDomain/GLOBEX#2]

**Comment by Markraxner** [comment]
genauere Infos hab ich net. i hab das buch und den einen artikel als quelle genommen, aber den artikel gibts online nicht mehr
brauchst beim buch no genauere quellenangaben?

**Comment by IntegralDomain** [comment]
publisher und year sollten noch ausgefüllt werden. bis jetzt stehen da nur platzhalter drin

**Comment by IntegralDomain** [comment]
danke
